{
	"document_title": "Security update for python-paramiko",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2018:0844-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2018-03-29T12:01:19Z",
				"description": "current"
			}
		},
		"initial_release_date": "2018-03-29T12:01:19Z",
		"current_release_date": "2018-03-29T12:01:19Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-paramiko",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-paramiko fixes the following issues:\n\n- CVE-2018-7750: Fixed transport.py in the SSH server implementation of Paramiko that does not properly check whether authentication is completed before processing other requests (bsc#1085276).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-OpenStack-Cloud-7-2018-566,SUSE-OpenStack-Cloud-Magnum-Orchestration-7-2018-566,SUSE-Storage-4-2018-566",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2018/suse-su-20180844-1/",
			"description": "Link for SUSE-SU-2018:0844-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-security-announce/2018-03/msg00071.html",
			"description": "E-Mail link for SUSE-SU-2018:0844-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1085276",
			"description": "SUSE Bug 1085276"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2018-7750/",
			"description": "SUSE CVE CVE-2018-7750 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Enterprise Storage 4",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Enterprise Storage 4",
						"full_product_name": {
							"text": "SUSE Enterprise Storage 4",
							"product_id": "SUSE Enterprise Storage 4",
							"cpe": "cpe:/o:suse:ses:4"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 7",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 7",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 7",
							"product_id": "SUSE OpenStack Cloud 7",
							"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-paramiko-2.0.8-3.3.1",
				"full_product_name": {
					"text": "python-paramiko-2.0.8-3.3.1",
					"product_id": "python-paramiko-2.0.8-3.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-paramiko-2.0.8-3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Enterprise Storage 4"
			},
			{
				"product_reference": "python-paramiko-2.0.8-3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "transport.py in the SSH server implementation of Paramiko before 1.17.6, 1.18.x before 1.18.5, 2.0.x before 2.0.8, 2.1.x before 2.1.5, 2.2.x before 2.2.3, 2.3.x before 2.3.2, and 2.4.x before 2.4.1 does not properly check whether authentication is completed before processing other requests, as demonstrated by channel-open. A customized SSH client can simply skip the authentication step.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2018-7750",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Enterprise Storage 4:python-paramiko-2.0.8-3.3.1",
						"SUSE OpenStack Cloud 7:python-paramiko-2.0.8-3.3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "10",
					"vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2018/suse-su-20180844-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2018-7750.html",
					"description": "CVE-2018-7750"
				},
				{
					"url": "https://bugzilla.suse.com/1085276",
					"description": "SUSE Bug 1085276"
				},
				{
					"url": "https://bugzilla.suse.com/1111151",
					"description": "SUSE Bug 1111151"
				}
			]
		}
	]
}
