{
	"document_title": "Security update for python-wxPython",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2024:3964-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-11-09T16:39:53Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-11-09T16:39:53Z",
		"current_release_date": "2024-11-09T16:39:53Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-wxPython",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-wxPython fixes the following issues:\n\nSecurity issue fixed: \n\n- CVE-2024-50602: Fixed a denial of service in the vendored libexpat's XML_ResumeParser function (bsc#1232590).\n\nNon-security issues fixed:\n\n- rebuilt for python 3.11 (bsc#1228252).\n- add repack script, do not include packaging/ dir in sources\n- Reduce complexity by not rewriting subpackages at all.\n- Appease factory-auto bot about package src name.\n- Add additional patches fixing the situation with Python 3.10\n  compatibility.\n- Split out the TW python3 flavors into multibuild using the\n  python_subpackage_only mechanism: Multiple python3 flavors\n  sequentially require too much space and time in one build.\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2024-3964,openSUSE-SLE-15.6-2024-3964",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20243964-1/",
			"description": "Link for SUSE-SU-2024:3964-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-November/019803.html",
			"description": "E-Mail link for SUSE-SU-2024:3964-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1228252",
			"description": "SUSE Bug 1228252"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1232590",
			"description": "SUSE Bug 1232590"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-50602/",
			"description": "SUSE CVE CVE-2024-50602 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.6",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.6",
						"full_product_name": {
							"text": "openSUSE Leap 15.6",
							"product_id": "openSUSE Leap 15.6",
							"cpe": "cpe:/o:opensuse:leap:15.6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python311-wxPython-4.1.1-150400.3.8.1",
				"full_product_name": {
					"text": "python311-wxPython-4.1.1-150400.3.8.1",
					"product_id": "python311-wxPython-4.1.1-150400.3.8.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-wxPython-lang-4.1.1-150400.3.8.1",
				"full_product_name": {
					"text": "python311-wxPython-lang-4.1.1-150400.3.8.1",
					"product_id": "python311-wxPython-lang-4.1.1-150400.3.8.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python311-wxPython-4.1.1-150400.3.8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			},
			{
				"product_reference": "python311-wxPython-lang-4.1.1-150400.3.8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.6"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "An issue was discovered in libexpat before 2.6.4. There is a crash within the XML_ResumeParser function because XML_StopParser can stop/suspend an unstarted parser.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-50602",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.6:python311-wxPython-4.1.1-150400.3.8.1",
						"openSUSE Leap 15.6:python311-wxPython-lang-4.1.1-150400.3.8.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "5.5",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20243964-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-50602.html",
					"description": "CVE-2024-50602"
				},
				{
					"url": "https://bugzilla.suse.com/1232579",
					"description": "SUSE Bug 1232579"
				}
			]
		}
	]
}
