{
	"document_title": "Security update for python-Django",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2024:2817-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-08-07T13:32:44Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-08-07T13:32:44Z",
		"current_release_date": "2024-08-07T13:32:44Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Django",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Django fixes the following issues:\n\n- CVE-2024-42005: Fixed SQL injection in QuerySet.values() and values_list() (bsc#1228629)\n- CVE-2024-41989: Fixed Memory exhaustion in django.utils.numberformat.floatformat() (bsc#1228630)\n- CVE-2024-41990: Fixed denial-of-service vulnerability in django.utils.html.urlize() (bsc#1228631)\n- CVE-2024-41991: Fixed another denial-of-service vulnerability in django.utils.html.urlize() (bsc#1228632)\n- CVE-2022-28346: Fixed SQL injection in QuerySet.annotate(),aggregate() and extra() (bsc#1198398)\n- CVE-2019-12308: Fixed XSS in AdminURLFieldWidget (bsc#1136468)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2024-2817,openSUSE-SLE-15.5-2024-2817",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/",
			"description": "Link for SUSE-SU-2024:2817-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-August/019139.html",
			"description": "E-Mail link for SUSE-SU-2024:2817-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1136468",
			"description": "SUSE Bug 1136468"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1198398",
			"description": "SUSE Bug 1198398"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1228629",
			"description": "SUSE Bug 1228629"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1228630",
			"description": "SUSE Bug 1228630"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1228631",
			"description": "SUSE Bug 1228631"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1228632",
			"description": "SUSE Bug 1228632"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-12308/",
			"description": "SUSE CVE CVE-2019-12308 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2022-28346/",
			"description": "SUSE CVE CVE-2022-28346 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-41989/",
			"description": "SUSE CVE CVE-2024-41989 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-41990/",
			"description": "SUSE CVE CVE-2024-41990 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-41991/",
			"description": "SUSE CVE CVE-2024-41991 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-42005/",
			"description": "SUSE CVE CVE-2024-42005 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.5",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.5",
						"full_product_name": {
							"text": "openSUSE Leap 15.5",
							"product_id": "openSUSE Leap 15.5",
							"cpe": "cpe:/o:opensuse:leap:15.5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python3-Django-2.0.7-150000.1.27.1",
				"full_product_name": {
					"text": "python3-Django-2.0.7-150000.1.27.1",
					"product_id": "python3-Django-2.0.7-150000.1.27.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python3-Django-2.0.7-150000.1.27.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 1.11 before 1.11.21, 2.1 before 2.1.9, and 2.2 before 2.2.2. The clickable Current URL value displayed by the AdminURLFieldWidget displays the provided value without validating it as a safe URL. Thus, an unvalidated value stored in the database, or a value provided as a URL query parameter payload, could result in an clickable JavaScript link.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-12308",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.27.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "6.1",
					"vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-12308.html",
					"description": "CVE-2019-12308"
				},
				{
					"url": "https://bugzilla.suse.com/1136468",
					"description": "SUSE Bug 1136468"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 2.2 before 2.2.28, 3.2 before 3.2.13, and 4.0 before 4.0.4. QuerySet.annotate(), aggregate(), and extra() methods are subject to SQL injection in column aliases via a crafted dictionary (with dictionary expansion) as the passed **kwargs.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2022-28346",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.27.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.3",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2022-28346.html",
					"description": "CVE-2022-28346"
				},
				{
					"url": "https://bugzilla.suse.com/1198398",
					"description": "SUSE Bug 1198398"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The floatformat template filter is subject to significant memory consumption when given a string representation of a number in scientific notation with a large exponent.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-41989",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.27.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-41989.html",
					"description": "CVE-2024-41989"
				},
				{
					"url": "https://bugzilla.suse.com/1228629",
					"description": "SUSE Bug 1228629"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-41990",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.27.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-41990.html",
					"description": "CVE-2024-41990"
				},
				{
					"url": "https://bugzilla.suse.com/1228630",
					"description": "SUSE Bug 1228630"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize and urlizetrunc template filters, and the AdminURLFieldWidget widget, are subject to a potential denial-of-service attack via certain inputs with a very large number of Unicode characters.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-41991",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.27.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-41991.html",
					"description": "CVE-2024-41991"
				},
				{
					"url": "https://bugzilla.suse.com/1228631",
					"description": "SUSE Bug 1228631"
				}
			]
		},
		{
			"notes": [
				{
					"text": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. QuerySet.values() and values_list() methods on models with a JSONField are subject to SQL injection in column aliases via a crafted JSON object key as a passed *arg.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-42005",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.5:python3-Django-2.0.7-150000.1.27.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "8.1",
					"vector_v_3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242817-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-42005.html",
					"description": "CVE-2024-42005"
				},
				{
					"url": "https://bugzilla.suse.com/1228632",
					"description": "SUSE Bug 1228632"
				}
			]
		}
	]
}
