{
	"document_title": "Security update for python-reportlab",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2023:4048-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2023-10-11T09:28:40Z",
				"description": "current"
			}
		},
		"initial_release_date": "2023-10-11T09:28:40Z",
		"current_release_date": "2023-10-11T09:28:40Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-reportlab",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-reportlab fixes the following issues:\n\n- CVE-2019-19450: Fixed an issue which allowed remote code execution via start_unichar in paraparser.py evaluating untrusted user input. (bsc#1215560)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2023-4048,SUSE-SLE-WE-12-SP5-2023-4048",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2023/suse-su-20234048-1/",
			"description": "Link for SUSE-SU-2023:4048-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016630.html",
			"description": "E-Mail link for SUSE-SU-2023:4048-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1215560",
			"description": "SUSE Bug 1215560"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-19450/",
			"description": "SUSE CVE CVE-2019-19450 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Workstation Extension 12 SP5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Workstation Extension 12 SP5",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Workstation Extension 12 SP5",
							"product_id": "SUSE Linux Enterprise Workstation Extension 12 SP5",
							"cpe": "cpe:/o:suse:sle-we:12:sp5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-reportlab-2.7-3.16.1",
				"full_product_name": {
					"text": "python-reportlab-2.7-3.16.1",
					"product_id": "python-reportlab-2.7-3.16.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-reportlab-2.7-3.16.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Workstation Extension 12 SP5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "paraparser in ReportLab before 3.5.31 allows remote code execution because start_unichar in paraparser.py evaluates untrusted user input in a unichar element in a crafted XML document with '<unichar code=\"' followed by arbitrary Python code, a similar issue to CVE-2019-17626.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-19450",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Workstation Extension 12 SP5:python-reportlab-2.7-3.16.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "7.7",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2023/suse-su-20234048-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-19450.html",
					"description": "CVE-2019-19450"
				},
				{
					"url": "https://bugzilla.suse.com/1215560",
					"description": "SUSE Bug 1215560"
				}
			]
		}
	]
}
