{
	"document_title": "Security update for python-Jinja2",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2021:14644-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-02-25T17:43:18Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-02-25T17:43:18Z",
		"current_release_date": "2021-02-25T17:43:18Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Jinja2",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Jinja2 fixes the following issues:\n\n- CVE-2020-28493: Improve the speed of the 'urlize' filter by reducing regex\n    backtracking. Email matching requires a word character at the start of the\n    domain part, and only word characters in the TLD. (bsc#1181944)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "pubclsp3-python-Jinja2-14644,slesctsp3-python-Jinja2-14644,slesctsp4-python-Jinja2-14644",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2021/suse-su-202114644-1/",
			"description": "Link for SUSE-SU-2021:14644-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2021-February/008377.html",
			"description": "E-Mail link for SUSE-SU-2021:14644-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1181944",
			"description": "SUSE Bug 1181944"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2020-28493/",
			"description": "SUSE CVE CVE-2020-28493 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server 11 SP3-CLIENT-TOOLS",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server 11 SP3-CLIENT-TOOLS",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server 11 SP3-CLIENT-TOOLS",
							"product_id": "SUSE Linux Enterprise Server 11 SP3-CLIENT-TOOLS",
							"cpe": "cpe:/a:suse:sle-clienttools:11:sp3"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server 11 SP4-CLIENT-TOOLS",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server 11 SP4-CLIENT-TOOLS",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server 11 SP4-CLIENT-TOOLS",
							"product_id": "SUSE Linux Enterprise Server 11 SP4-CLIENT-TOOLS",
							"cpe": "cpe:/a:suse:sle-clienttools:11:sp4"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Server 11-PUBCLOUD",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Server 11-PUBCLOUD",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Server 11-PUBCLOUD",
							"product_id": "SUSE Linux Enterprise Server 11-PUBCLOUD"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Jinja2-2.6-2.19.5.1",
				"full_product_name": {
					"text": "python-Jinja2-2.6-2.19.5.1",
					"product_id": "python-Jinja2-2.6-2.19.5.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Jinja2-2.6-2.19.5.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 11 SP3-CLIENT-TOOLS"
			},
			{
				"product_reference": "python-Jinja2-2.6-2.19.5.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 11 SP4-CLIENT-TOOLS"
			},
			{
				"product_reference": "python-Jinja2-2.6-2.19.5.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Server 11-PUBCLOUD"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation. This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-28493",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Server 11 SP3-CLIENT-TOOLS:python-Jinja2-2.6-2.19.5.1",
						"SUSE Linux Enterprise Server 11 SP4-CLIENT-TOOLS:python-Jinja2-2.6-2.19.5.1",
						"SUSE Linux Enterprise Server 11-PUBCLOUD:python-Jinja2-2.6-2.19.5.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2021/suse-su-202114644-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2020-28493.html",
					"description": "CVE-2020-28493"
				},
				{
					"url": "https://bugzilla.suse.com/1181944",
					"description": "SUSE Bug 1181944"
				}
			]
		}
	]
}
