{
	"document_title": "Security update for python-codecov",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2022:2752-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2022-08-10T11:35:42Z",
				"description": "current"
			}
		},
		"initial_release_date": "2022-08-10T11:35:42Z",
		"current_release_date": "2022-08-10T11:35:42Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-codecov",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-codecov fixes the following issues:\n\n- CVE-2019-10800: Fixed sanitization of gcov arguments before being being provided to the popen method (bsc#1201494).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2022-2752,openSUSE-SLE-15.3-2022-2752,openSUSE-SLE-15.4-2022-2752",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20222752-1/",
			"description": "Link for SUSE-SU-2022:2752-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2022-August/011881.html",
			"description": "E-Mail link for SUSE-SU-2022:2752-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1201494",
			"description": "SUSE Bug 1201494"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-10800/",
			"description": "SUSE CVE CVE-2019-10800 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.3",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.3",
						"full_product_name": {
							"text": "openSUSE Leap 15.3",
							"product_id": "openSUSE Leap 15.3",
							"cpe": "cpe:/o:opensuse:leap:15.3"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.4",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.4",
						"full_product_name": {
							"text": "openSUSE Leap 15.4",
							"product_id": "openSUSE Leap 15.4",
							"cpe": "cpe:/o:opensuse:leap:15.4"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python2-codecov-2.0.15-150100.3.3.1",
				"full_product_name": {
					"text": "python2-codecov-2.0.15-150100.3.3.1",
					"product_id": "python2-codecov-2.0.15-150100.3.3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-codecov-2.0.15-150100.3.3.1",
				"full_product_name": {
					"text": "python3-codecov-2.0.15-150100.3.3.1",
					"product_id": "python3-codecov-2.0.15-150100.3.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python2-codecov-2.0.15-150100.3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-codecov-2.0.15-150100.3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-codecov-2.0.15-150100.3.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.4"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "This affects the package codecov before 2.0.16. The vulnerability occurs due to not sanitizing gcov arguments before being being provided to the popen method.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-10800",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.3:python2-codecov-2.0.15-150100.3.3.1",
						"openSUSE Leap 15.3:python3-codecov-2.0.15-150100.3.3.1",
						"openSUSE Leap 15.4:python3-codecov-2.0.15-150100.3.3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4",
					"vector_v_2": "AV:N/AC:L/Au:S/C:P/I:N/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "6.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2022/suse-su-20222752-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-10800.html",
					"description": "CVE-2019-10800"
				},
				{
					"url": "https://bugzilla.suse.com/1201494",
					"description": "SUSE Bug 1201494"
				}
			]
		}
	]
}
