{
	"document_title": "Security update for python-brotlipy",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2023:3670-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2023-09-19T09:50:34Z",
				"description": "current"
			}
		},
		"initial_release_date": "2023-09-19T09:50:34Z",
		"current_release_date": "2023-09-19T09:50:34Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-brotlipy",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-brotlipy fixes the following issues:\n\n- CVE-2020-8927: Fixed integer overflow when input chunk is larger than 2GiB (bsc#1175825).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2023-3670,SUSE-SLE-Module-Public-Cloud-12-2023-3670",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2023/suse-su-20233670-1/",
			"description": "Link for SUSE-SU-2023:3670-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-updates/2023-September/031549.html",
			"description": "E-Mail link for SUSE-SU-2023:3670-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1175825",
			"description": "SUSE Bug 1175825"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2020-8927/",
			"description": "SUSE CVE CVE-2020-8927 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Linux Enterprise Module for Public Cloud 12",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Linux Enterprise Module for Public Cloud 12",
						"full_product_name": {
							"text": "SUSE Linux Enterprise Module for Public Cloud 12",
							"product_id": "SUSE Linux Enterprise Module for Public Cloud 12",
							"cpe": "cpe:/o:suse:sle-module-public-cloud:12"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-brotlipy-0.6.0-2.6.1",
				"full_product_name": {
					"text": "python-brotlipy-0.6.0-2.6.1",
					"product_id": "python-brotlipy-0.6.0-2.6.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-brotlipy-0.6.0-2.6.1",
				"full_product_name": {
					"text": "python3-brotlipy-0.6.0-2.6.1",
					"product_id": "python3-brotlipy-0.6.0-2.6.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-brotlipy-0.6.0-2.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 12"
			},
			{
				"product_reference": "python3-brotlipy-0.6.0-2.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Linux Enterprise Module for Public Cloud 12"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "A buffer overflow exists in the Brotli library versions prior to 1.0.8 where an attacker controlling the input length of a \"one-shot\" decompression request to a script can trigger a crash, which happens when copying over chunks of data larger than 2 GiB. It is recommended to update your Brotli library to 1.0.8 or later. If one cannot update, we recommend to use the \"streaming\" API as opposed to the \"one-shot\" API, and impose chunk size limits.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-8927",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Linux Enterprise Module for Public Cloud 12:python-brotlipy-0.6.0-2.6.1",
						"SUSE Linux Enterprise Module for Public Cloud 12:python3-brotlipy-0.6.0-2.6.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "6.4",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:P/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.3",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2023/suse-su-20233670-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2020-8927.html",
					"description": "CVE-2020-8927"
				},
				{
					"url": "https://bugzilla.suse.com/1175825",
					"description": "SUSE Bug 1175825"
				}
			]
		}
	]
}
