{
	"document_title": "Security update for python-Babel",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2021:1553-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-12-10T09:49:43Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-12-10T09:49:43Z",
		"current_release_date": "2021-12-10T09:49:43Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Babel",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Babel fixes the following issues:\n\n- CVE-2021-42771: Fixed relative path traversal that may lead to arbitrary locale files loading and arbitrary code execution (bsc#1185768).\n\nThis update was imported from the SUSE:SLE-15-SP2:Update update project.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-2021-1553",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/WAKYSLN4RPESEDQ7LN7KPRMYQUFA4SYU/",
			"description": "E-Mail link for openSUSE-SU-2021:1553-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1185768",
			"description": "SUSE Bug 1185768"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-42771/",
			"description": "SUSE CVE CVE-2021-42771 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.2",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.2",
						"full_product_name": {
							"text": "openSUSE Leap 15.2",
							"product_id": "openSUSE Leap 15.2",
							"cpe": "cpe:/o:opensuse:leap:15.2"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Babel-doc-2.8.0-lp152.2.3.1",
				"full_product_name": {
					"text": "python-Babel-doc-2.8.0-lp152.2.3.1",
					"product_id": "python-Babel-doc-2.8.0-lp152.2.3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python2-Babel-2.8.0-lp152.2.3.1",
				"full_product_name": {
					"text": "python2-Babel-2.8.0-lp152.2.3.1",
					"product_id": "python2-Babel-2.8.0-lp152.2.3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-Babel-2.8.0-lp152.2.3.1",
				"full_product_name": {
					"text": "python3-Babel-2.8.0-lp152.2.3.1",
					"product_id": "python3-Babel-2.8.0-lp152.2.3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-Babel-doc-2.8.0-lp152.2.3.1",
				"full_product_name": {
					"text": "python3-Babel-doc-2.8.0-lp152.2.3.1",
					"product_id": "python3-Babel-doc-2.8.0-lp152.2.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Babel-doc-2.8.0-lp152.2.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			},
			{
				"product_reference": "python2-Babel-2.8.0-lp152.2.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			},
			{
				"product_reference": "python3-Babel-2.8.0-lp152.2.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			},
			{
				"product_reference": "python3-Babel-doc-2.8.0-lp152.2.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Babel.Locale in Babel before 2.9.1 allows attackers to load arbitrary locale .dat files (containing serialized Python objects) via directory traversal, leading to code execution.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-42771",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.2:python-Babel-doc-2.8.0-lp152.2.3.1",
						"openSUSE Leap 15.2:python2-Babel-2.8.0-lp152.2.3.1",
						"openSUSE Leap 15.2:python3-Babel-2.8.0-lp152.2.3.1",
						"openSUSE Leap 15.2:python3-Babel-doc-2.8.0-lp152.2.3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.2",
					"vector_v_2": "AV:L/AC:L/Au:N/C:C/I:C/A:C"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.8",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/WAKYSLN4RPESEDQ7LN7KPRMYQUFA4SYU/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-42771.html",
					"description": "CVE-2021-42771"
				},
				{
					"url": "https://bugzilla.suse.com/1185768",
					"description": "SUSE Bug 1185768"
				}
			]
		}
	]
}
