{
	"document_title": "python36-pip-20.2.4-1.8 on GA media",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2024:11251-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-06-15T00:00:00Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-06-15T00:00:00Z",
		"current_release_date": "2024-06-15T00:00:00Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "python36-pip-20.2.4-1.8 on GA media",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "These are all security issues fixed in the python36-pip-20.2.4-1.8 package on the GA media of openSUSE Tumbleweed.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-Tumbleweed-2024-11251",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2013-5123/",
			"description": "SUSE CVE CVE-2013-5123 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2014-8991/",
			"description": "SUSE CVE CVE-2014-8991 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2015-2296/",
			"description": "SUSE CVE CVE-2015-2296 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-20916/",
			"description": "SUSE CVE CVE-2019-20916 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python36-pip-20.2.4-1.8",
				"full_product_name": {
					"text": "python36-pip-20.2.4-1.8",
					"product_id": "python36-pip-20.2.4-1.8"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-pip-20.2.4-1.8",
				"full_product_name": {
					"text": "python38-pip-20.2.4-1.8",
					"product_id": "python38-pip-20.2.4-1.8"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-pip-20.2.4-1.8",
				"full_product_name": {
					"text": "python39-pip-20.2.4-1.8",
					"product_id": "python39-pip-20.2.4-1.8"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python36-pip-20.2.4-1.8",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-pip-20.2.4-1.8",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-pip-20.2.4-1.8",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The mirroring support (-M, --use-mirrors) in Python Pip before 1.5 uses insecure DNS querying and authenticity checks which allows attackers to perform man-in-the-middle attacks.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2013-5123",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python36-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python38-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python39-pip-20.2.4-1.8"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.9",
					"vector_v_3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2013-5123.html",
					"description": "CVE-2013-5123"
				},
				{
					"url": "https://bugzilla.suse.com/864406",
					"description": "SUSE Bug 864406"
				}
			]
		},
		{
			"notes": [
				{
					"text": "pip 1.3 through 1.5.6 allows local users to cause a denial of service (prevention of package installation) by creating a /tmp/pip-build-* file for another user.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2014-8991",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python36-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python38-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python39-pip-20.2.4-1.8"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "2.1",
					"vector_v_2": "AV:L/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.5",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2014-8991.html",
					"description": "CVE-2014-8991"
				},
				{
					"url": "https://bugzilla.suse.com/907038",
					"description": "SUSE Bug 907038"
				}
			]
		},
		{
			"notes": [
				{
					"text": "The resolve_redirects function in sessions.py in requests 2.1.0 through 2.5.3 allows remote attackers to conduct session fixation attacks via a cookie without a host value in a redirect.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2015-2296",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python36-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python38-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python39-pip-20.2.4-1.8"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "1.8",
					"vector_v_2": "AV:A/AC:H/Au:N/C:P/I:N/A:N"
				},
				"score_set_v_3": {},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2015-2296.html",
					"description": "CVE-2015-2296"
				},
				{
					"url": "https://bugzilla.suse.com/922448",
					"description": "SUSE Bug 922448"
				},
				{
					"url": "https://bugzilla.suse.com/926396",
					"description": "SUSE Bug 926396"
				}
			]
		},
		{
			"notes": [
				{
					"text": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-20916",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python36-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python38-pip-20.2.4-1.8",
						"openSUSE Tumbleweed:python39-pip-20.2.4-1.8"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "6.8",
					"vector_v_3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-20916.html",
					"description": "CVE-2019-20916"
				},
				{
					"url": "https://bugzilla.suse.com/1176262",
					"description": "SUSE Bug 1176262"
				}
			]
		}
	]
}
