{
	"document_title": "Security update for python3",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2021:4104-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-12-16T10:14:25Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-12-16T10:14:25Z",
		"current_release_date": "2021-12-16T10:14:25Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python3",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python3 fixes the following issues:\n\n- CVE-2021-3426: Fixed information disclosure via pydoc (bsc#1183374).\n- CVE-2021-3733: Fixed infinitely reading potential HTTP headers after a 100 Continue status response from the server (bsc#1189241).\n- CVE-2021-3737: Fixed ReDoS in urllib.request (bsc#1189287).\n\n- We do not require python-rpm-macros package (bsc#1180125).\n- Use versioned python-Sphinx to avoid dependency on other version of Python (bsc#1183858).\n- Stop providing 'python' symbol, which means python2 currently (bsc#1185588).\n- Modify Lib/ensurepip/__init__.py to contain the same version numbers as are in reality the ones in the bundled wheels (bsc#1187668).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-SLE-15.3-2021-4104",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/KYXM7YGLJSNOU4FYI3M2QXACCQ4SO3AE/",
			"description": "E-Mail link for openSUSE-SU-2021:4104-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1180125",
			"description": "SUSE Bug 1180125"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1183374",
			"description": "SUSE Bug 1183374"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1183858",
			"description": "SUSE Bug 1183858"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1185588",
			"description": "SUSE Bug 1185588"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1187668",
			"description": "SUSE Bug 1187668"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1189241",
			"description": "SUSE Bug 1189241"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1189287",
			"description": "SUSE Bug 1189287"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-3426/",
			"description": "SUSE CVE CVE-2021-3426 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-3733/",
			"description": "SUSE CVE CVE-2021-3733 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-3737/",
			"description": "SUSE CVE CVE-2021-3737 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.3",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.3",
						"full_product_name": {
							"text": "openSUSE Leap 15.3",
							"product_id": "openSUSE Leap 15.3",
							"cpe": "cpe:/o:opensuse:leap:15.3"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "libpython3_6m1_0-3.6.15-10.9.1",
				"full_product_name": {
					"text": "libpython3_6m1_0-3.6.15-10.9.1",
					"product_id": "libpython3_6m1_0-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "libpython3_6m1_0-32bit-3.6.15-10.9.1",
				"full_product_name": {
					"text": "libpython3_6m1_0-32bit-3.6.15-10.9.1",
					"product_id": "libpython3_6m1_0-32bit-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-3.6.15-10.9.1",
					"product_id": "python3-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-base-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-base-3.6.15-10.9.1",
					"product_id": "python3-base-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-curses-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-curses-3.6.15-10.9.1",
					"product_id": "python3-curses-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-dbm-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-dbm-3.6.15-10.9.1",
					"product_id": "python3-dbm-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-devel-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-devel-3.6.15-10.9.1",
					"product_id": "python3-devel-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-doc-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-doc-3.6.15-10.9.1",
					"product_id": "python3-doc-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-doc-devhelp-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-doc-devhelp-3.6.15-10.9.1",
					"product_id": "python3-doc-devhelp-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-idle-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-idle-3.6.15-10.9.1",
					"product_id": "python3-idle-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-testsuite-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-testsuite-3.6.15-10.9.1",
					"product_id": "python3-testsuite-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-tk-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-tk-3.6.15-10.9.1",
					"product_id": "python3-tk-3.6.15-10.9.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-tools-3.6.15-10.9.1",
				"full_product_name": {
					"text": "python3-tools-3.6.15-10.9.1",
					"product_id": "python3-tools-3.6.15-10.9.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "libpython3_6m1_0-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "libpython3_6m1_0-32bit-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-base-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-curses-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-dbm-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-devel-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-doc-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-doc-devhelp-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-idle-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-testsuite-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-tk-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"product_reference": "python3-tools-3.6.15-10.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers or is able to convince another local or adjacent user to start a pydoc server could access the server and use it to disclose sensitive information belonging to the other user that they would not normally be able to access. The highest risk of this flaw is to data confidentiality. This flaw affects Python versions before 3.8.9, Python versions before 3.9.3 and Python versions before 3.10.0a7.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-3426",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.3:libpython3_6m1_0-3.6.15-10.9.1",
						"openSUSE Leap 15.3:libpython3_6m1_0-32bit-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-base-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-curses-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-dbm-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-devel-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-doc-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-doc-devhelp-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-idle-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-testsuite-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-tk-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-tools-3.6.15-10.9.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "2.7",
					"vector_v_2": "AV:A/AC:L/Au:S/C:P/I:N/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.5",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/KYXM7YGLJSNOU4FYI3M2QXACCQ4SO3AE/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-3426.html",
					"description": "CVE-2021-3426"
				},
				{
					"url": "https://bugzilla.suse.com/1183374",
					"description": "SUSE Bug 1183374"
				}
			]
		},
		{
			"notes": [
				{
					"text": "There's a flaw in urllib's AbstractBasicAuthHandler class. An attacker who controls a malicious HTTP server that an HTTP client (such as web browser) connects to, could trigger a Regular Expression Denial of Service (ReDOS) during an authentication request with a specially crafted payload that is sent by the server to the client. The greatest threat that this flaw poses is to application availability.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-3733",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.3:libpython3_6m1_0-3.6.15-10.9.1",
						"openSUSE Leap 15.3:libpython3_6m1_0-32bit-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-base-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-curses-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-dbm-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-devel-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-doc-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-doc-devhelp-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-idle-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-testsuite-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-tk-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-tools-3.6.15-10.9.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4",
					"vector_v_2": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "4",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/KYXM7YGLJSNOU4FYI3M2QXACCQ4SO3AE/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-3733.html",
					"description": "CVE-2021-3733"
				},
				{
					"url": "https://bugzilla.suse.com/1189287",
					"description": "SUSE Bug 1189287"
				}
			]
		},
		{
			"notes": [
				{
					"text": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-3737",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.3:libpython3_6m1_0-3.6.15-10.9.1",
						"openSUSE Leap 15.3:libpython3_6m1_0-32bit-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-base-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-curses-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-dbm-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-devel-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-doc-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-doc-devhelp-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-idle-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-testsuite-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-tk-3.6.15-10.9.1",
						"openSUSE Leap 15.3:python3-tools-3.6.15-10.9.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.1",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:N/A:C"
				},
				"score_set_v_3": {
					"base_score_v_3": "6.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/KYXM7YGLJSNOU4FYI3M2QXACCQ4SO3AE/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-3737.html",
					"description": "CVE-2021-3737"
				},
				{
					"url": "https://bugzilla.suse.com/1189241",
					"description": "SUSE Bug 1189241"
				}
			]
		}
	]
}
